/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.AdminMenu;

import javax.swing.JOptionPane;
import negocio.DTO.UnidadAcademicaDTO;
import negocio.logica.UnidadAcademicaNegocio;

/**
 *
 * @author nomar
 */
public class FrmInsertarUnidad extends javax.swing.JFrame {

    /**
     * Creates new form FrmInsertarUnidad
     */
    public FrmInsertarUnidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centroDeComputo = new javax.swing.JLabel();
        reporte = new javax.swing.JLabel();
        btnAtras = new javax.swing.JLabel();
        fldUnidad = new javax.swing.JTextField();
        centroDeComputo1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        centroDeComputo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        centroDeComputo.setForeground(new java.awt.Color(255, 255, 255));
        centroDeComputo.setText("Unidad");
        getContentPane().add(centroDeComputo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        reporte.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        reporte.setForeground(new java.awt.Color(255, 255, 255));
        reporte.setText("Insertar");
        getContentPane().add(reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnAtras.png"))); // NOI18N
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, -1, -1));
        getContentPane().add(fldUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 270, 50));

        centroDeComputo1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        centroDeComputo1.setForeground(new java.awt.Color(255, 255, 255));
        centroDeComputo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        centroDeComputo1.setText("Unidad");
        getContentPane().add(centroDeComputo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 230, 1000, -1));

        btnAgregar.setBackground(new java.awt.Color(0, 204, 0));
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, 140, 60));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundGeneral.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        // TODO add your handling code here:
        new FrmAdminMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String nombre = fldUnidad.getText();
        
        if (nombre.matches(".*\\d.*") || nombre.isEmpty())
        {JOptionPane.showMessageDialog(this, "Un nombre de unidad no puede contener numeros, caracteres especiales o estar vacío" );}
        else{
        
        UnidadAcademicaDTO unidad = new UnidadAcademicaDTO();
        unidad.setNombre(nombre);
        
        UnidadAcademicaNegocio unidadNegocio = new UnidadAcademicaNegocio();
        
        unidadNegocio.guardarUnidadAcademica(unidad);
        
        JOptionPane.showMessageDialog(this, "Unidad agregada con exito!" );
        
        FrmAdminMenu frm = new FrmAdminMenu();
        frm.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel btnAtras;
    private javax.swing.JLabel centroDeComputo;
    private javax.swing.JLabel centroDeComputo1;
    private javax.swing.JTextField fldUnidad;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel reporte;
    // End of variables declaration//GEN-END:variables
}
