/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.AdminMenu.GestionarAlumno;

import java.util.List;
import javax.swing.JOptionPane;
import negocio.DTO.CarreraDTO;
import negocio.DTO.EstudianteDTO;
import negocio.logica.CarreraNegocio;
import negocio.logica.EstudianteNegocio;
import org.eclipse.persistence.internal.jpa.parsing.jpql.antlr.JPQLParser;
import utilerias.CaesarCipher;

/**
 *
 * @author nomar
 */
public class FrmEditarAlumnoPopUp extends javax.swing.JFrame {

    CarreraNegocio carreraNegocio = new CarreraNegocio();
    EstudianteNegocio estudianteNegocio = new EstudianteNegocio();
    CaesarCipher encriptar = new CaesarCipher();

    EstudianteDTO estudiante;

    /**
     * Creates new form FrmAgregarAlumno
     */
    public FrmEditarAlumnoPopUp() {
    }

    public FrmEditarAlumnoPopUp(EstudianteDTO estudiante) {
        initComponents();
        this.estudiante = estudiante;

        mostrarInformacionActualEstudiante();
        llenarBoxCarreras(carreraNegocio.buscarCarreras());
    }

    public void mostrarInformacionActualEstudiante() {
        campoTextoNombre.setText(estudiante.getNombre());
        campoTextoApellidoPaterno.setText(estudiante.getApellidoPaterno());
        campoTextoApellidoMaterno.setText(estudiante.getApellidoMaterno());
        campoTextoContrasenia.setText(estudiante.getContrasenia());
    }

    /**
     * Metodo que se encarga de llenar el comboBox con las carreras de la base
     * de datos
     *
     * @param carrera Lista de carreras que hay en una unidad academica
     */
    private void llenarBoxCarreras(List<CarreraDTO> carrera) {
        int i = 0;
        while (carrera.size() > i) {
            comboBoxCarrera.addItem(carrera.get(i).getNombre());
            i++;
        }
    }

    /**
     * Metodo que obtiene una CarreraDTO en base a un index de un comboBox
     *
     * @param carrera Lista de carreras que hay en una unidad academica
     * @param comboBoxIndex Index de el combo box a utilizar
     * @return
     */
    private CarreraDTO obtenerCarreraDTOfromComboBox(List<CarreraDTO> carrera, int comboBoxIndex) {
        int i = 0;
        try {
            while (carrera.size() > i) {
                if (carrera.get(i).getId() == comboBoxIndex) {
                    return carrera.get(i);
                } else {
                    i++;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error insesperado: " + e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblApellidoMaterno = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidoPaterno = new javax.swing.JLabel();
        comboBoxEstatusInscripcion = new javax.swing.JComboBox<>();
        campoTextoNombre = new javax.swing.JTextField();
        campoTextoApellidoPaterno = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        campoTextoApellidoMaterno = new javax.swing.JTextField();
        lblEstatusInscripcion = new javax.swing.JLabel();
        comboBoxCarrera = new javax.swing.JComboBox<>();
        lblContrasenia = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        campoTextoContrasenia = new javax.swing.JPasswordField();
        lblCarrera = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblApellidoMaterno.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidoMaterno.setText("Apellido Materno");
        getContentPane().add(lblApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        lblApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblApellidoPaterno.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidoPaterno.setText("Apellido Paterno");
        getContentPane().add(lblApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        comboBoxEstatusInscripcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inscrito", "Baja" }));
        comboBoxEstatusInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEstatusInscripcionActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxEstatusInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 125, 30));
        getContentPane().add(campoTextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 220, 30));
        getContentPane().add(campoTextoApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 220, 30));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Editar Alumno");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));
        getContentPane().add(campoTextoApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 220, 30));

        lblEstatusInscripcion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEstatusInscripcion.setForeground(new java.awt.Color(255, 255, 255));
        lblEstatusInscripcion.setText("Estatus Inscripcion");
        getContentPane().add(lblEstatusInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        comboBoxCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCarreraActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 125, 30));

        lblContrasenia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasenia.setText("Contraseña");
        getContentPane().add(lblContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        btnEditar.setBackground(new java.awt.Color(255, 153, 0));
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));
        getContentPane().add(campoTextoContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 220, 30));

        lblCarrera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCarrera.setForeground(new java.awt.Color(255, 255, 255));
        lblCarrera.setText("Carrera");
        getContentPane().add(lblCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroundChico.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo que cierra el frame
     *
     * @param evt presionar el boton cancelar
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Boton que agrega un estudiante con su carrera en la base de datos.
     *
     * @param evt presionar el boton agregar
     */
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String nombre = campoTextoNombre.getText();
        String aPaterno = campoTextoApellidoPaterno.getText();
        String aMaterno = campoTextoApellidoMaterno.getText();
        String contrasenia = campoTextoContrasenia.getText();
        String estatusCarrera = comboBoxEstatusInscripcion.getSelectedItem().toString();

        try {
            estudiante.setNombre(nombre);
            estudiante.setApellidoPaterno(aPaterno);
            estudiante.setApellidoMaterno(aMaterno);
            estudiante.setContrasenia(contrasenia);
            estudiante.setEstatusInscripcion(estatusCarrera);

            CarreraNegocio carreraNegocio = new CarreraNegocio();
            int carrera = comboBoxCarrera.getSelectedIndex() + 1;
//        obtenerCarreraDTOfromComboBox(carreraNegocio.buscarCarreras(), carrera);
            CarreraDTO carreraDTO = obtenerCarreraDTOfromComboBox(carreraNegocio.buscarCarreras(), carrera);

            estudiante.setCarrera(carreraDTO);

            estudianteNegocio.modificarEstudiante(estudiante);
            JOptionPane.showMessageDialog(this, "El estudiante se ha editado correctamente.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error inesperado: \n" + e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * Boton que reinicia los campos de texto del frame
     *
     * @param evt presiona el boton "reiniciar"
     */
    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        campoTextoNombre.setText("");
        campoTextoApellidoPaterno.setText("");
        campoTextoApellidoMaterno.setText("");
        campoTextoContrasenia.setText("");
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void comboBoxCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCarreraActionPerformed

    private void comboBoxEstatusInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEstatusInscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxEstatusInscripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditarAlumnoPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditarAlumnoPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditarAlumnoPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditarAlumnoPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditarAlumnoPopUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JTextField campoTextoApellidoMaterno;
    private javax.swing.JTextField campoTextoApellidoPaterno;
    private javax.swing.JPasswordField campoTextoContrasenia;
    private javax.swing.JTextField campoTextoNombre;
    private javax.swing.JComboBox<String> comboBoxCarrera;
    private javax.swing.JComboBox<String> comboBoxEstatusInscripcion;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblApellidoMaterno;
    private javax.swing.JLabel lblApellidoPaterno;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblEstatusInscripcion;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
