/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import negocio.DTO.EstudianteDTO;
import negocio.logica.EstudianteNegocio;

/**
 *
 * @author PC
 */
public class FrmComputadora extends javax.swing.JFrame {

    /**
     * Creates new form FrmComputadora
     */
    
    EstudianteNegocio estudianteNegocio = new EstudianteNegocio();
    
    public FrmComputadora() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumComputadora = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnDesbloquear = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumComputadora.setBackground(new java.awt.Color(187, 187, 187));
        txtNumComputadora.setFont(new java.awt.Font("Arial", 1, 128)); // NOI18N
        txtNumComputadora.setForeground(new java.awt.Color(153, 153, 153));
        txtNumComputadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNumComputadora.setText("52");
        getContentPane().add(txtNumComputadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, 164, 155));

        txtContrasenia.setBackground(new java.awt.Color(114, 114, 114));
        txtContrasenia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 630, 260, 40));

        txtId.setBackground(new java.awt.Color(114, 114, 114));
        txtId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 540, 260, 40));

        btnDesbloquear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnDesbloquear.png"))); // NOI18N
        btnDesbloquear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDesbloquear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesbloquearMouseClicked(evt);
            }
        });
        getContentPane().add(btnDesbloquear, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 690, 157, 41));

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_Computadora.png"))); // NOI18N
        getContentPane().add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesbloquearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesbloquearMouseClicked
        System.out.println("boton aceptar click!");
        
        EstudianteDTO eD = new EstudianteDTO();
        if (txtId.getText().matches(".*\\D+.*") || txtId.getText().isEmpty())
        {JOptionPane.showMessageDialog(this, "Un ID no puede contener letras, caracteres especiales o estar vacío" );}
        else{
            
        Long id = Long.decode(txtId.getText());
        eD.setId(Long.decode(txtId.getText()));
        eD.setContrasenia(txtContrasenia.getText());
        EstudianteDTO estudiante = estudianteNegocio.buscarEstudiante(id);

        if (estudiante != null)
        {

            if(estudiante.getContrasenia().equals(eD.getContrasenia())){
        
            this.dispose();

            
        } else{

            JOptionPane.showMessageDialog(this, "Contraseña incorrecta" );          
                
            }
        }
        else{
        
            JOptionPane.showMessageDialog(this, "No existe un estudiante con ese ID o contraseña" );
            
        }
        }
    }//GEN-LAST:event_btnDesbloquearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmComputadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmComputadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmComputadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmComputadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmComputadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDesbloquear;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtId;
    private javax.swing.JLabel txtNumComputadora;
    // End of variables declaration//GEN-END:variables
}
