/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.AdminMenu.GestionarCarrera;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import negocio.DTO.CarreraDTO;
import negocio.logica.CarreraNegocio;

/**
 *
 * @author nomar
 */
public class FrmEditarCarrera extends javax.swing.JFrame {

    CarreraNegocio carreraNegocio = new CarreraNegocio();
    
    CarreraDTO carrera;
    
    public FrmEditarCarrera() {
    }
    
    /**
     * Creates new form FrmEditarCarrera
     */
    public FrmEditarCarrera(CarreraDTO carrera) {
        initComponents();
        
        this.carrera = carrera;
        mostrarInformacionActualCarrera();
    }

    public void mostrarInformacionActualCarrera() {
        campoTextoNombreCarrera.setText(carrera.getNombre());
        
        Date tiempoDiarioDate = carrera.getTiempoDiario(); 
        SimpleDateFormat formato = new SimpleDateFormat("HH:mm:ss"); 
        String tiempoDiarioString = formato.format(tiempoDiarioDate);

        campoTextoTiempo.setText(tiempoDiarioString);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campoTextoTiempo = new javax.swing.JTextField();
        campoTextoNombreCarrera = new javax.swing.JTextField();
        nombreCarrera = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Editar Carrera");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        btnEditar.setBackground(new java.awt.Color(255, 153, 51));
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tiempo en minutos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));
        getContentPane().add(campoTextoTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 230, 30));
        getContentPane().add(campoTextoNombreCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 230, 30));

        nombreCarrera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombreCarrera.setForeground(new java.awt.Color(255, 255, 255));
        nombreCarrera.setText("Nombre de la carrera");
        getContentPane().add(nombreCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroundChico.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        
        String nombreCarrera = campoTextoNombreCarrera.getText(); // Campo para el nombre de la carrera
        String tiempoDiarioStr = campoTextoTiempo.getText(); // Campo para el tiempo diario

        try {
            // Convierte el tiempo diario de String a Date
            SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss"); // Define el formato esperado
            Date tiempoDiario = timeFormat.parse(tiempoDiarioStr); // Convierte el String a Date

            // Establece los atributos de la carrera
            carrera.setNombre(nombreCarrera);
            carrera.setTiempoDiario(tiempoDiario); // Establece el tiempo diario como Date

            // Inicializa CarreraNegocio y modifica la carrera
            CarreraNegocio carreraNegocio = new CarreraNegocio();
            carreraNegocio.modificarCarrera(carrera);

            JOptionPane.showMessageDialog(this, "La Carrera se ha editado correctamente.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            dispose();

        } catch (ParseException parseException) {
            JOptionPane.showMessageDialog(this, "El formato del tiempo diario es incorrecto. Use HH:mm:ss.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error inesperado: \n" + e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnEditarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JTextField campoTextoNombreCarrera;
    private javax.swing.JTextField campoTextoTiempo;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombreCarrera;
    // End of variables declaration//GEN-END:variables
}
